accounts/urls.py
from django.urls import path
from .views import activate, addto_wish_list, change_password, forgot_password, login, logout, my_orders, profile, registerUser, dashboard, reset_password, reset_password_validate, wishlist


urlpatterns = [
    path('register/', registerUser, name= 'registerUser'),
    path('dashboard/', dashboard, name= 'dashboard'),
    path('my_orders/', my_orders, name= 'my_orders'),
    path('wish_list/', wishlist, name= 'wish_list'),
    path('profile/', profile, name= 'profile'),
    path('login/', login, name= 'login'),
    path('logout/', logout, name= 'logout'),
    path('activate/<uidb64>/<token>', activate, name= 'activate'),

    path('change_password/', change_password , name='change_password' ),

    path('reset_password_validate/<uidb64>/<token>/', reset_password_validate, name='reset_password_validate' ),
    path('forgot_password/', forgot_password, name='forgot_password' ),
    path('reset_password/', reset_password, name='reset_password' ),


    path('addto_wish_list/<int:product_id>', addto_wish_list, name= 'addto_wish_list'),

]

carts/urls.py
from django.urls import path
from .views import cart, add_cart, decrease_cart, remove_cart, increase_cart


urlpatterns = [
    path('', cart, name= 'cart'),
    path('add_cart/<int:product_id>/', add_cart, name= 'add_cart'),
    path('decrease_cart/', decrease_cart, name= 'decrease_cart'),
    path('increase_cart/', increase_cart, name= 'increase_cart'),
    path('remove_cart/', remove_cart, name= 'remove_cart'),
    
]

furnitureX/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home, about
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('jet/', include('jet.urls')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('accounts/', include('accounts.urls')),
    path('marketplace/', include('marketplace.urls')),
    path('cart/', include('carts.urls')),
    path('order/', include('orders.urls')),
    path('contact/', include('contact.urls')),
    path('analytics/', include('analytics.urls')),

    path('social_accounts/', include('allauth.urls')),
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class UserManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError('User must have an email address')

        if not username:
            raise ValueError('User must have an username')

        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, email, username, password):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            password = password,
            first_name = first_name,
            last_name = last_name,
        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user



class User(AbstractBaseUser):
    first_name      = models.CharField(max_length=50)
    last_name       = models.CharField(max_length=50)
    username        = models.CharField(max_length=50, unique=True)
    email           = models.EmailField(max_length=100, unique=True, blank=True)
    phone_number    = models.CharField(max_length=50, blank=True)

    # required
    date_joined         = models.DateTimeField(auto_now_add=True)
    last_login          = models.DateTimeField(auto_now_add=True)
    is_admin            = models.BooleanField(default=False)
    is_staff            = models.BooleanField(default=False)
    is_active           = models.BooleanField(default=True)
    is_email_varified   = models.BooleanField(default=False)
    is_superadmin       = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = UserManager()

    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return self.first_name

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    profile_picture = models.ImageField(blank=True, upload_to='userprofile')
    address = models.CharField(max_length=250)
    country = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    pin_code = models.CharField(max_length=50)

    
    def __str__(self):
        return self.user.first_name

marketplace/models.py
import os
from django.db import models
from django.utils.safestring import mark_safe

from accounts.models import User
from django.db.models import Avg, Count

from math import floor, ceil, modf

# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField(max_length=250, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    class Meta:
        """Meta definition for MODELNAME."""

        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        
    def __str__(self):
        return self.category_name
    
class Brand(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/brands')
    def __str__(self):
        return self.brand_title

class Colour(models.Model):
    title = models.CharField(max_length=100)
    colour_code = models.CharField(max_length=100, blank=True)
    def __str__(self):
        return self.title

class Size(models.Model):
    title = models.CharField(max_length=100)
    def __str__(self):
        return self.title

def offer_image(instanse, filename):
    upload_to = "images/Deals/"
    ext =  filename.split('.')['-1']
    #get filename
    if instanse.name:
        filename = '{}.{}'.format(instanse.name, ext)
        return os.path.join(upload_to, filename)
    
class Offer(models.Model):
    name = models.CharField(max_length=50)
    discount = models.PositiveIntegerField()
    image = models.ImageField(upload_to=offer_image, blank=True, null=True)

    def __str__(self):
        return self.name
def discount_image(instanse, filename):
    upload_to = "images/Deals/"
    ext =  filename.split('.')['-1']
    #get filename
    if instanse.name:
        filename = '{}.{}'.format(instanse.name, ext)
        return os.path.join(upload_to, filename)
    
class Discount(models.Model):
    name = models.CharField(max_length=50)
    discount = models.PositiveIntegerField()
    image = models.ImageField(upload_to= discount_image, blank=True, null=True)

    def __str__(self):
        return self.name
def deal_image(instanse, filename):
    upload_to = "images/Deals/"
    ext =  filename.split('.')['-1']
    #get filename
    if instanse.name:
        filename = '{}.{}'.format(instanse.name, ext)
        return os.path.join(upload_to, filename)
    
class Deal(models.Model):
    name = models.CharField(max_length=50)
    discount = models.PositiveIntegerField()
    image = models.ImageField(upload_to= deal_image, blank=True, null=True)

    def __str__(self):
        return self.name

class Products(models.Model):
    product_title = models.CharField(max_length=100, unique= True)
    image = models.ImageField(upload_to='images/products/', blank =True, null= True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    description = models.TextField(max_length=250, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    slug = models.SlugField(max_length=100, unique=True)
    stock = models.IntegerField()
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, null=True, blank=True)
    colour = models.ForeignKey(Colour, on_delete=models.CASCADE, null=True, blank=True)
    size = models.ForeignKey(Size, on_delete=models.CASCADE, null=True, blank=True)
    is_featured = models.BooleanField(default=False)
    is_available = models.BooleanField(default=True)
    on_sale = models.BooleanField(default=False)
    offer = models.ForeignKey(Offer, on_delete=models.CASCADE, null=True, blank=True)
    discount = models.ForeignKey(Discount, on_delete=models.CASCADE, null=True, blank=True)
    deal = models.ForeignKey(Deal, on_delete=models.CASCADE, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        """Meta definition for Product."""

        verbose_name = 'Product'
        verbose_name_plural = 'Products'
    
    def save(self, *args, **kwargs):
        super(Products, self).save(*args, **kwargs)
        product_variations = ProductVariation.objects.filter(product = self)
        if product_variations.count() > 0:
            for product in product_variations:
                if product.product.on_sale:
                    discount_price = product.get_discount_price()
                    if isinstance(discount_price, float):
                        dec = modf(discount_price)[0]
                        if dec < 0.5:
                            price = floor(discount_price)
                        else:
                            price = ceil(discount_price)
                    else:
                        price = discount_price
                    product.discount_price = price
                else:
                    product.discount_price = product.price
                product.save()



    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg
    
    def countReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count
    
    def __str__(self):
        return self.product_title
    
class ProductVariation(models.Model):
    slug = models.SlugField(max_length=100, unique=True, null=True, blank=True)
    product = models.ForeignKey(Products, on_delete=models.CASCADE )
    colour = models.ForeignKey(Colour, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/products/', null = True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount_price = models.PositiveIntegerField(null=True, blank=True)
    sell_price = models.IntegerField()

    def __str__(self):
        return self.product.product_title
    
    def get_discount_price(self):
        product = self.product
        if product.on_sale:
            if product.discount:
                percent = product.discount.discount
            elif product.deal:
                percent = product.deal.discount
            elif product.offer:
                percent = product.offer.discount
            else:
                percent = 0
            price_redu = (percent*self.price)/100
            price = self.price - price_redu
            return price
        else:
            return self.price

    def save(self, *args, **kwargs):
        self.discount_price = self.get_discount_price()
        super(ProductVariation, self).save(*args, **kwargs)
    
    def discounted_price(self):
        return ((self.price)*(self.discount))/100
    
    def sell_price(self):
        return (self.price)-(self.discounted_price)
    
    def image_tag(self):
        return mark_safe('<img src="%s" height="50" width="50" />' %(self.image.url))


class Tax(models.Model):
    tax_type = models.CharField(max_length=50)
    tax_percentage = models.DecimalField(max_digits=4, decimal_places=2, verbose_name="Tax-Percentage(%)")
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.tax_type
    

class ReviewRating(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    user  = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=100, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now= True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.subject


class WishList(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    user  = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.product_title

accounts/forms.py
from django import forms

from accounts.validators import allow_only_image_validator
from .models import User, UserProfile

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'phone_number', 'username', 'password']

    
    def clean(self):
        cleaned_data = super(UserRegistrationForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError("Password doesn't match.")
            

class User_Profile_Form(forms.ModelForm):
    address = forms.CharField(widget= forms.TextInput(attrs={'placeholder' : 'start typing...', 'required' : 'required'}))
    profile_picture = forms.FileField(widget=forms.FileInput(attrs={'class': 'border-btn input-btn'}), validators=[allow_only_image_validator])
    
    class Meta:
        model = UserProfile
        fields = ['profile_picture', 'address', 'city','country', 'state', 'pin_code']

    def __init__(self, *args, **kwargs):
        super(User_Profile_Form, self).__init__(*args, **kwargs)
        for field in self.fields:
            if not field == 'profile_picture':
                self.fields[field].widget.attrs['class'] = 'form-control'

    


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'phone_number']


    def __init__(self, *args, **kwargs):
        super(UserInfoForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

templates/accounts/change_password.html
{% extends 'base.html' %}
{% block content %}

{% load static %}
{% include 'includes/navbar.html' %}

{% include 'includes/alerts.html' %}


<!-- Main Section Start -->
<div class="main-section">
	<div class="page-section account-header buyer-logged-in my-5 py-5">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
					<!-- SIDE BAR  -->
					{% include 'includes/sidebar.html' %}
				</div>
                <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                    <div class="user-dashboard loader-holder">
                        <div class="user-holder">
                            <h5 class="text-uppercase">Change Password</h5>
							<hr>
                                <form action="{% url 'change_password' %}" method="POST">
                                    {% csrf_token %}
                                    <div class="form-fields-set">
                                        <ul>
                                            <li>
                                                <div class="input-box">
                                                    <div class="single-input-fields">
                                                        <label >Current Password</label>
                                                        <input type="text" class="form-control" id="add1" name="current_password" required placeholder="Current Password"/>
                                                        
                                                    </div>
                                                    <div class="single-input-fields">
                                                        <label>New Password</label>
                                                        <input type="text" class="form-control" id="add1" name="new_password" required placeholder="New Password"/>
                                                        
                                                    </div>
                                                    <div class="single-input-fields">
                                                        <label>Confirm Password</label>
                                                        <input type="text" class="form-control" id="add1" name="confirm_password" required placeholder="Confirm Password"/>
                                                        
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                        <div>
                                            <div class="field-holder">
                                                <div class="payment-holder input-button-loader py-5">
                                                    <button class="btn" type="submit" > Update Password</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->










                


{% include 'includes/footer.html' %}

{% endblock content %}

templates/accounts/dashboard.html
{% extends 'base.html' %}
{% block content %}

{% load static %}
{% include 'includes/navbar.html' %}

{% include 'includes/alerts.html' %}

<!-- Main Section Start -->
<div class="main-section">
	<div class="page-section account-header buyer-logged-in my-5 py-5">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
					<!-- SIDE BAR  -->
					{% include 'includes/sidebar.html' %}
				</div>
				<div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
					<div class="user-dashboard">
						<div class="user-holder">
							<h5 class="text-uppercase py-2">Overview</h5>
							<div class="row">
								<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
									<div class="card">
										<div class="card-header">
											<p class="text-center">Total orders</p>
										</div>
										<div class="card-body text-center">
											<a href="#"><h5 class="card-title">{{order_count}}</h5></a>
										</div>
									</div>
									
								</div>
								<div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
									<div class="card">
										<div class="card-header">
											<p>Logged in as : {{request.user.email}}</p>
										</div>
										<div class="card-body text-center">
											<a href="{% url 'profile' %}"><h5 class="card-title">Edit profile</h5></a>
										</div>
									</div>
									
								</div>
								
							</div>
							<br>
							<div class="row">
								<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
									<div class="user-suggest-list listing simple">
										<table class="table table-striped table-hover " id="myOrdersTable">
											<thead class="table-bordered">
												<tr>
													<th scope="col">#Order</th>
													<th scope="col">Name</th>
													<th scope="col">Total</th>
													<th scope="col">Status</th>
													<th scope="col">Date</th>
													<th scope="col">Action</th>
												</tr>
											</thead>
											<tbody>
												
												{% for order in orders %}
												<tr>
													<td scope=""><a href="{% url 'order_details' order.order_number %}" class="text-dark"><b>{{order.order_number}}</b></a></td>
													<td>{{order.full_name}}</td>
													<td>${{order.order_total}}</td>
													<td>{{order.status}}</td>
													<td>{{order.created_at}}</td>
													<td><a href="{% url 'order_details' order.order_number %}" class="btn btn-danger">Details</a></td>
												</tr>
												{% endfor %}
											</tbody>
										</table>
										
									</div>
									
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Main Section End -->



{% include 'includes/footer.html' %}

{% endblock content %}

templates/accounts/forgot_password.html
{% extends 'base.html' %}

{% block content %}
{% include 'includes/alerts.html' %}

<main class="login-bg">

    <div class="login-form-area">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-7 col-lg-8">
                    <div class="login-form">
                        
                        <div class="login-heading">
                            <span>Forgot Password</span>
                            <p>Enter your email address to continue.</p>
                        </div>
                        <form action="{% url 'forgot_password' %}" method="POST">
                            {% csrf_token %}
                            <div class="input-box">
                                <div class="single-input-fields">
                                    <label>Email Address</label>
                                    <input name="email" type="text" placeholder="Email address">
                                </div>
                                
                            </div>
                            <div class="errors float-left">
                                <ul class="error_list">
                                    {% for field in form %}
                                        {% if field.errors %}
                                            {% for error in field.errors %}
                                                <li style="color:red;">{{error}}</li>
                                            {% endfor %}
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            </div>

                            <div class="login-footer">
                                <p>Don’t have an account? <a href="{% url 'registerUser' %}">Sign Up</a> here</p>
                                <button type="submit" class="submit-btn3">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</main>


{% endblock content %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
{% include 'includes/alerts.html' %}

{% load socialaccount %}
{% providers_media_js %}

<main class="login-bg">

    <div class="login-form-area">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-7 col-lg-8">
                    <div class="login-form">
                        
                        <div class="login-heading">
                            <span>Login</span>
                            <p>Enter Login details to get access</p>
                        </div>
                        <form action="{% url 'login' %}" method="POST">
                            {% csrf_token %}
                            <div class="input-box">
                                <div class="single-input-fields">
                                    <label>Email Address</label>
                                    <input name="email" type="text" placeholder="Username / Email address">
                                </div>
                                <div class="single-input-fields">
                                    <label>Password</label>
                                    <input name="password" type="password" placeholder="Enter Password">
                                </div>
                                <div class="single-input-fields login-check">
                                    <input type="checkbox" id="fruit1" name="keep-log">
                                    <label for="fruit1">Keep me logged in</label>
                                    <a href="{% url 'forgot_password' %}" class="f-right">Forgot Password?</a>
                                </div>
                            </div>
                            <div class="errors float-left">
                                <ul class="error_list">
                                    {% for field in form %}
                                        {% if field.errors %}
                                            {% for error in field.errors %}
                                                <li style="color:red;">{{error}}</li>
                                            {% endfor %}
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            </div>
                                                    
                        <div class="contact-section-furnitureX">
                            <div class="form-section">
                                <div class="extra-login clearfix">
                                    <span>Or Login With</span>
                                </div>
                                <div class="clearfix"></div>
                                <ul class="social-list text-center">
                                    {% comment %} <li><a href="{% provider_login_url 'facebook' method='oauth2' %}" class="facebook-bg"><i class="ti-facebook"></i><span>Facebook</span></a></li> {% endcomment %}
                                    <li><a href="{% provider_login_url 'facebook' method='js_sdk' %}" class="facebook-bg"><i class="ti-facebook"></i><span>Facebook</span></a></li>
                                    <li><a href="{% provider_login_url 'google' method='oauth2'%}" class="google-bg"><i class="fa fa-google google-i"></i><span>Google</span></a></li>
                                </ul>

                                <div class="login-footer">
                                    <p>Don’t have an account? <a href="{% url 'registerUser' %}">Sign Up</a> here</p>
                                    <button type="submit" class="submit-btn3">Login</button>
                                </div>
                            </div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</main>


{% endblock content %}

templates/accounts/wish_list.html
{% extends 'base.html' %}
{% block content %}

{% load static %}
{% include 'includes/navbar.html' %}


<!-- Main Section Start -->
<div class="main-section">
	<div class="page-section account-header buyer-logged-in my-5 py-5">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
					<!-- SIDE BAR  -->
					{% include 'includes/sidebar.html' %}
				</div>
				<div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
					<div class="user-dashboard loader-holder">
						
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="row">
								<div class="element-title has-border right-filters-row">
									<h5>Wish List</h5>
									<hr>
								</div>
							</div>
						</div>
							<div class="row">
								<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
									<div class="user-orders-list">
										<div class="responsive-table">
											<table class="table table-striped table-hover " id="myOrdersTable">
												<thead class="table-bordered">
													<tr>
														<th scope="col">#Order</th>
														<th scope="col">Name</th>
														<th scope="col">Date</th>
														<th scope="col">Details</th>
													</tr>
												</thead>
												<tbody>
													{% for item in wish_list %}
													<tr>
														<td scope="">
                                                            <a href="{% url 'product_detail' item.product.category.slug item.product.slug %}" class="text-dark">
                                                                <img src="{{item.product.productvariation_set.first.image.url}}" alt="product image" style="width: 100px !important; position: relative;" >
                                                            </a>
                                                        </td>
														<td> <br> {{item.product.product_title}}</td>
														<td> <br> {{item.created_at}}</td>
														<td> <a href="{% url 'product_detail' item.product.category.slug item.product.slug %}" class="btn">Product Details</a></td>
													</tr>
													{% endfor %}
												</tbody>
											</table>
										</div>
									</div>
								</div>
							</div>

							<!--  table end  -->
							<!--
							<ul class="pagination">
								<li class="active"><a>1</a></li>
								<li><a href="#">2</a></li>
								<li><a href="#">3</a></li>
								<li><span class="page-numbers dots">…</span></li>
								<li><a href="#">5</a></li>
								<li><a href="#">Next </a></li>
							</ul> 
							-->
						</div>
					</div>
				</div>
            </div>
        </div>
    </div>
</div>

{% include 'includes/footer.html' %}

{% endblock content %}